Added about page
ImagineThisNHS/ImagineThisNHS.github.io pull request #5
Opened 2021-03-21 17:53 UTC by dinojs

2021-03-21 18:59 UTC, KashSingh1 commented
Mark Binghao as a TA, possibly by putting TA in brackets next to his name.

2021-03-25 06:48 UTC, lukasotocerny requested changes

2021-03-25 06:48 UTC, lukasotocerny commented on getting started/about.md
> +## 3. Supervisors
I'd add section `Teaching assistants` and reference Binghao there

2021-03-25 06:48 UTC, lukasotocerny commented on getting started/about.md
> +### Version 2 Team
I would mention that this team are UCL students of the MSc Software Systems Engineering programme, working on this project as part of COMP0102 in 2020-2021 cohort.

2021-03-25 06:48 UTC, lukasotocerny commented on getting started/about.md
> +### Version 1 Team
Similarly as with us, just mention that students are part of SSE programme, and summer 2020 industrial project.

2021-03-26 21:12 UTC, lukasotocerny approved these changes
LGTM

2021-03-28 22:59 UTC, merged